/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;
import modelos.Usuario;
import modelos.Correo;
import modelos.Seguridad;
import modelos.Salario;

/**
 *
 * @author DELL
 */
public class Menu extends javax.swing.JFrame {
    private Usuario usuario;
    private Correo correo;
    private Seguridad seguridad;
    private Salario salario;

    /**
     * Creates new form menu
     */
    public Menu() {
        initComponents();
        usuario = new Usuario("1", "Marco", "Sanint", "Hombre", 123456789, "marcosanint8@gmail.com", "1234", 25000);
        correo = new Correo();
        seguridad = new Seguridad();
        salario = new Salario();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btContraseña = new javax.swing.JToggleButton();
        ctContraseña = new javax.swing.JTextField();
        btCalculoSalario = new javax.swing.JToggleButton();
        btMandarCorreo = new javax.swing.JToggleButton();
        ctCorreo = new javax.swing.JTextField();
        btInfoUsuario = new javax.swing.JToggleButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtRespuestas = new javax.swing.JTextArea();
        ctHorasTrabajadas = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Menu de opciones");

        btContraseña.setText("Intentar Contraseña");
        btContraseña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btContraseñaActionPerformed(evt);
            }
        });

        ctContraseña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ctContraseñaActionPerformed(evt);
            }
        });

        btCalculoSalario.setText("Calcular Salario");
        btCalculoSalario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCalculoSalarioActionPerformed(evt);
            }
        });

        btMandarCorreo.setText("Mandar Correo");
        btMandarCorreo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btMandarCorreoActionPerformed(evt);
            }
        });

        ctCorreo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ctCorreoActionPerformed(evt);
            }
        });

        btInfoUsuario.setText("Sacar info Usuario");
        btInfoUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btInfoUsuarioActionPerformed(evt);
            }
        });

        txtRespuestas.setColumns(20);
        txtRespuestas.setRows(5);
        jScrollPane1.setViewportView(txtRespuestas);

        ctHorasTrabajadas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ctHorasTrabajadasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btCalculoSalario, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ctContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btContraseña)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(btMandarCorreo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ctCorreo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btInfoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ctHorasTrabajadas, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 105, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(177, 177, 177))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1)
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btInfoUsuario)
                        .addGap(18, 18, 18)
                        .addComponent(btMandarCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ctCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ctContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btCalculoSalario)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ctHorasTrabajadas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(83, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btContraseñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btContraseñaActionPerformed
        String inputPassword = ctContraseña.getText();
        String realPassword = usuario.getPassword();
        String verificacionContraseña = seguridad.validarContraseña(inputPassword, realPassword);
        txtRespuestas.setText(verificacionContraseña);
    }//GEN-LAST:event_btContraseñaActionPerformed

    private void ctContraseñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ctContraseñaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ctContraseñaActionPerformed

    private void btMandarCorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btMandarCorreoActionPerformed
        String mensaje = ctCorreo.getText();
        String gmail = usuario.getGmail();
        String correoCompleto = correo.enviarCorreoUsuario(gmail, mensaje);
        System.out.println(usuario.getGmail());
        txtRespuestas.setText(correoCompleto);
    }//GEN-LAST:event_btMandarCorreoActionPerformed

    private void ctCorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ctCorreoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ctCorreoActionPerformed

    private void btInfoUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btInfoUsuarioActionPerformed
        txtRespuestas.setText(usuario.obtenerInfoUsuario());
    }//GEN-LAST:event_btInfoUsuarioActionPerformed

    private void ctHorasTrabajadasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ctHorasTrabajadasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ctHorasTrabajadasActionPerformed

    private void btCalculoSalarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCalculoSalarioActionPerformed
        double porHora = usuario.getTarifaHora();
        double horas = Double.parseDouble(ctHorasTrabajadas.getText());
        double salarioTotal = salario.calcularSalario(horas, porHora);
        txtRespuestas.setText(salarioTotal + " $");
        
    }//GEN-LAST:event_btCalculoSalarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btCalculoSalario;
    private javax.swing.JToggleButton btContraseña;
    private javax.swing.JToggleButton btInfoUsuario;
    private javax.swing.JToggleButton btMandarCorreo;
    private javax.swing.JTextField ctContraseña;
    private javax.swing.JTextField ctCorreo;
    private javax.swing.JTextField ctHorasTrabajadas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtRespuestas;
    // End of variables declaration//GEN-END:variables
}
